project:
  type: website
  output-dir: docs

website:
  title: "NL"
  favicon: https://cdn-icons-png.flaticon.com/512/235/235349.png
  navbar:
    logo: https://cdn-icons-png.flaticon.com/512/235/235349.png
    left:
      - href: index.qmd
        text: Home
      - href: otherprojects.qmd
      - href: Hobbies.qmd
      - href: reflection.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left